name: Teste dos endpoints [AXIOS]

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-axios:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar Server
        run: |
          nohup node app.js & sleep 3

      - name: Teste do endpoint
        run: |
          resposta=$(curl -s "https://viacep.com.br/ws/08161360/json/")
          if echo "$resposta" | grep -q '"logradouro"'; then
            echo "$resposta"
          else
            echo "Erro ao buscar cep"
            exit 1
          fi
